FROM php:8.3-apache


RUN    docker-php-ext-install  pdo pdo_mysql
#COPY public/phpinfo.php /var/www/html


#LABEL authors="M.Martinez"
#RUN apt update && \
#    apt install -y php php-mysql libapache2-mod-php
#RUN a2enmod php8.2
#
#COPY ./pokemon.html /usr/local/apache2/htdocs/
#COPY ./phpinfo.php /usr/local/apache2/htdocs/
